import * as THREE from 'three';
import { FBXLoader } from 'three/addons/loaders/FBXLoader.js';
const $=s=>document.querySelector(s), viewer=$('#viewer'),empty=$('#empty'),fileInput=$('#fileInput'),loadButton=$('#loadButton'),playButton=$('#playButton'),runtimeStatus=$('#runtimeStatus'),errorBox=$('#error'),timeline=$('#timeline'),timelineTime=$('#timelineTime'),timelinePercent=$('#timelinePercent'),facingReadout=$('#facingReadout'),cameraReadout=$('#cameraReadout'),bookmarkName=$('#bookmarkName'),saveBookmark=$('#saveBookmark'),bookmarkList=$('#bookmarkList');
const facingButtons=[...document.querySelectorAll('[data-facing]')],cameraButtons=[...document.querySelectorAll('[data-camera]')];
const fields={file:$('#fFile'),mesh:$('#fMesh'),skeleton:$('#fSkeleton'),anim:$('#fAnim'),duration:$('#fDuration'),inPlace:$('#fInPlace'),root:$('#fRoot')};
const scene=new THREE.Scene();scene.background=new THREE.Color(0x0c0e12);const camera=new THREE.OrthographicCamera(-1,1,1,-1,.01,1000),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;viewer.prepend(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x303744,2.1));const key=new THREE.DirectionalLight(0xffffff,2.8);key.position.set(4,7,5);scene.add(key);const floor=new THREE.Mesh(new THREE.PlaneGeometry(20,20),new THREE.MeshStandardMaterial({color:0x171b22,roughness:1}));floor.rotation.x=-Math.PI/2;scene.add(floor);const grid=new THREE.GridHelper(10,20,0x3b424f,0x252a33);grid.position.y=.002;scene.add(grid);const origin=new THREE.Group();scene.add(origin);
let currentModel=null,skeletonHelper=null,mixer=null,action=null,clip=null,rootProbe=null,currentFileName='',playing=true,modelCenter=new THREE.Vector3(0,1,0),modelHeight=2,currentFacing='N',currentCamera='ISO';const clock=new THREE.Clock(),bookmarks=[];
const facingAngles={N:-135,NE:180,E:135,SE:90,S:45,SW:0,W:-45,NW:-90};const cameraPresets={ISO:{id:'GAMEPLAY_ISO_45',dir:new THREE.Vector3(1,1,1).normalize()},FRONT:{id:'TECH_FRONT',dir:new THREE.Vector3(0,0,1)},BACK:{id:'TECH_BACK',dir:new THREE.Vector3(0,0,-1)},LEFT:{id:'TECH_LEFT',dir:new THREE.Vector3(-1,0,0)},RIGHT:{id:'TECH_RIGHT',dir:new THREE.Vector3(1,0,0)},TOP:{id:'TECH_TOP',dir:new THREE.Vector3(0,1,0)}};
function fact(el,text,kind=''){el.textContent=text;el.className=kind}function err(m=''){errorBox.textContent=m;errorBox.classList.toggle('show',!!m)}
function frustum(){const w=Math.max(1,viewer.clientWidth),h=Math.max(1,renderer.domElement.clientHeight||520),a=w/h,hh=Math.max(modelHeight*.72,1.2);camera.top=hh;camera.bottom=-hh;camera.left=-hh*a;camera.right=hh*a;camera.updateProjectionMatrix()}function resize(){const w=viewer.clientWidth,h=Math.max(520,Math.round(w*.76));renderer.setSize(w,h,false);frustum()}new ResizeObserver(resize).observe(viewer);resize();
function applyCamera(){const p=cameraPresets[currentCamera],d=Math.max(modelHeight*3,4);camera.position.copy(modelCenter).addScaledVector(p.dir,d);camera.up.set(0,currentCamera==='TOP'?0:1,currentCamera==='TOP'?-1:0);camera.lookAt(modelCenter);camera.near=.01;camera.far=d*10;frustum();cameraReadout.textContent=p.id;cameraButtons.forEach(b=>b.classList.toggle('active',b.dataset.camera===currentCamera))}
function setFacing(id){if(!(id in facingAngles))return;currentFacing=id;origin.rotation.y=THREE.MathUtils.degToRad(facingAngles[id]);origin.updateMatrixWorld(true);facingReadout.textContent=id;facingButtons.forEach(b=>b.classList.toggle('active',b.dataset.facing===id))}function setCamera(id){if(!(id in cameraPresets))return;currentCamera=id;applyCamera()}
function resetTimeline(){timeline.disabled=true;timeline.value='0';timelineTime.textContent='0.000 / 0.000 s';timelinePercent.textContent='0.0 %'}function updateTimeline(t=0){if(!clip||clip.duration<=0){resetTimeline();return}const d=clip.duration,x=Math.max(0,Math.min(t,d)),n=x/d;timeline.value=String(Math.round(n*1000));timelineTime.textContent=`${x.toFixed(3)} / ${d.toFixed(3)} s`;timelinePercent.textContent=`${(n*100).toFixed(1)} %`}
function dispose(){if(currentModel){origin.remove(currentModel);currentModel.traverse(o=>{o.geometry?.dispose?.();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose?.())})}if(skeletonHelper)origin.remove(skeletonHelper);currentModel=skeletonHelper=mixer=action=clip=rootProbe=null;currentFileName='';resetTimeline();saveBookmark.disabled=true}
function analyze(m){let meshCount=0,skinnedCount=0,boneCount=0;m.traverse(o=>{if(o.isMesh)meshCount++;if(o.isSkinnedMesh)skinnedCount++;if(o.isBone)boneCount++});return{meshCount,skinnedCount,boneCount}}function locateRoot(m){for(const n of ['mixamorig:Hips','Hips','mixamorig:Root','Root']){const x=m.getObjectByName(n);if(x)return x}return m}
function testInPlace(m,c){if(!c)return null;const p=locateRoot(m),mx=new THREE.AnimationMixer(m),a=mx.clipAction(c);a.play();mx.setTime(0);m.updateMatrixWorld(true);const x=p.getWorldPosition(new THREE.Vector3());mx.setTime(Math.max(0,c.duration-.0001));m.updateMatrixWorld(true);const y=p.getWorldPosition(new THREE.Vector3());mx.stopAllAction();return Math.hypot(y.x-x.x,y.z-x.z)}
function setPlaying(v){if(!action)return;playing=v;action.paused=!v;playButton.textContent=v?'Pause':'Weiter';runtimeStatus.textContent=v?'Animation läuft':'Animation pausiert';clock.getDelta()}
function seekNormalized(n){if(!mixer||!clip||!action)return;n=Math.max(0,Math.min(n,1));const t=n>=1?Math.max(0,clip.duration-.000001):clip.duration*n;playing=false;action.paused=false;action.time=t;mixer.update(0);action.paused=true;playButton.textContent='Weiter';currentModel.updateMatrixWorld(true);updateTimeline(t);runtimeStatus.textContent=`Position gewählt · ${(n*100).toFixed(1)} %`;clock.getDelta()}
function captureBookmark(){if(!clip||!action)return;const name=(bookmarkName.value||'').trim()||`REF${bookmarks.length+1}`,time=Math.max(0,Math.min(action.time,clip.duration)),normalized=clip.duration?time/clip.duration:0;const ref={name,file:currentFileName,clip:clip.name||'unnamed',time,normalized,facing:currentFacing,camera:cameraPresets[currentCamera].id,cameraKey:currentCamera};const i=bookmarks.findIndex(b=>b.name===name);if(i>=0)bookmarks[i]=ref;else bookmarks.push(ref);renderBookmarks();runtimeStatus.textContent=`Referenz ${name} gespeichert`;const m=name.match(/^FR(\d+)$/i);if(m)bookmarkName.value=`FR${Number(m[1])+1}`}
function restoreBookmark(ref){if(!clip||ref.file!==currentFileName){runtimeStatus.textContent=`${ref.name}: passende FBX zuerst laden`;return}setFacing(ref.facing);setCamera(ref.cameraKey);seekNormalized(ref.normalized);runtimeStatus.textContent=`${ref.name} wiederhergestellt · ${(ref.normalized*100).toFixed(1)} %`}
function renderBookmarks(){bookmarkList.innerHTML='';if(!bookmarks.length){bookmarkList.innerHTML='<span class="status">Noch keine Referenz gespeichert.</span>';return}for(const r of bookmarks){const row=document.createElement('div');row.className='bookmark';const main=document.createElement('div');main.className='bookmark-main';const title=document.createElement('b');title.textContent=r.name;const meta=document.createElement('span');meta.textContent=`${r.clip} · ${r.time.toFixed(3)} s · ${(r.normalized*100).toFixed(1)} % · ${r.facing} · ${r.camera}`;main.append(title,meta);const b=document.createElement('button');b.className='btn';b.textContent='Laden';b.addEventListener('click',()=>restoreBookmark(r));row.append(main,b);bookmarkList.append(row)}}
async function loadFBX(file){err();runtimeStatus.textContent='FBX wird gelesen …';playButton.disabled=true;dispose();currentFileName=file.name;fact(fields.file,file.name);try{const model=new FBXLoader().parse(await file.arrayBuffer(),'');model.name=file.name;const s=analyze(model);fact(fields.mesh,s.meshCount?`${s.meshCount} Mesh${s.meshCount===1?'':'es'} (${s.skinnedCount} skinned)`:'KEIN sichtbares Mesh',s.meshCount?'ok':'bad');fact(fields.skeleton,s.boneCount?`${s.boneCount} Bones`:'keine Bones erkannt',s.boneCount?'ok':'bad');clip=model.animations?.[0]||null;fact(fields.anim,clip?`${model.animations.length} Clip${model.animations.length===1?'':'s'} · ${clip.name||'unnamed'}`:'kein Clip erkannt',clip?'ok':'bad');fact(fields.duration,clip?`${clip.duration.toFixed(3)} s`:'–');model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});currentModel=model;origin.add(model);if(s.boneCount&&!s.meshCount){skeletonHelper=new THREE.SkeletonHelper(model);origin.add(skeletonHelper)}model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(model);if(!box.isEmpty())model.position.y-=box.min.y;model.updateMatrixWorld(true);const fb=new THREE.Box3().setFromObject(model),size=fb.getSize(new THREE.Vector3()),center=fb.getCenter(new THREE.Vector3());modelHeight=Math.max(size.y,1);modelCenter.set(center.x,Math.max(modelHeight*.5,center.y),center.z);setFacing(currentFacing);applyCamera();if(clip){const drift=testInPlace(model,clip);fact(fields.inPlace,`${drift<=.01?'PASS':'WARN'} · horizontale Drift ${drift.toFixed(4)}`,drift<=.01?'ok':'warn');mixer=new THREE.AnimationMixer(model);action=mixer.clipAction(clip);action.play();action.setLoop(THREE.LoopRepeat,Infinity);playing=true;playButton.textContent='Pause';playButton.disabled=false;timeline.disabled=false;saveBookmark.disabled=false;action.time=0;mixer.update(0);updateTimeline(0)}else{fact(fields.inPlace,'nicht prüfbar','warn')}rootProbe=locateRoot(model);model.updateMatrixWorld(true);const p=rootProbe.getWorldPosition(new THREE.Vector3());fact(fields.root,`${p.x.toFixed(3)} / ${p.z.toFixed(3)}`);empty.classList.add('hidden');runtimeStatus.textContent=s.meshCount&&clip?'Runtime-Intake geladen · Animation läuft':'Asset geladen · Intake prüfen'}catch(e){console.error(e);err(`FBX konnte nicht geladen werden: ${e?.message||e}`);runtimeStatus.textContent='Laden fehlgeschlagen';empty.classList.remove('hidden')}}
loadButton.onclick=()=>fileInput.click();fileInput.onchange=()=>{const f=fileInput.files?.[0];if(f)loadFBX(f)};playButton.onclick=()=>setPlaying(!playing);timeline.oninput=timeline.onchange=()=>seekNormalized(Number(timeline.value)/1000);facingButtons.forEach(b=>b.onclick=()=>setFacing(b.dataset.facing));cameraButtons.forEach(b=>b.onclick=()=>setCamera(b.dataset.camera));saveBookmark.onclick=captureBookmark;bookmarkName.addEventListener('keydown',e=>{if(e.key==='Enter'&&!saveBookmark.disabled)captureBookmark()});setFacing('N');setCamera('ISO');
(function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);if(mixer&&playing){mixer.update(dt);updateTimeline(action?.time||0)}if(currentModel&&rootProbe){currentModel.updateMatrixWorld(true);const p=rootProbe.getWorldPosition(new THREE.Vector3());fact(fields.root,`${p.x.toFixed(3)} / ${p.z.toFixed(3)}`)}renderer.render(scene,camera)})();