export class GeometryControlEditor{
  constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.image=null;this.points={};this.selected=null;this.order=['head','neck','pelvis','lShoulder','lElbow','lWrist','rShoulder','rElbow','rWrist','lHip','lKnee','lAnkle','lToe','rHip','rKnee','rAnkle','rToe'];this.edges=[['head','neck'],['neck','pelvis'],['lShoulder','rShoulder'],['lShoulder','lElbow'],['lElbow','lWrist'],['rShoulder','rElbow'],['rElbow','rWrist'],['pelvis','lHip'],['pelvis','rHip'],['lHip','lKnee'],['lKnee','lAnkle'],['lAnkle','lToe'],['rHip','rKnee'],['rKnee','rAnkle'],['rAnkle','rToe']];canvas.addEventListener('click',e=>this.click(e))}
  async setImage(dataUrl){this.image=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=dataUrl});this.canvas.width=this.image.width;this.canvas.height=this.image.height;this.points={};this.selected=null;this.draw()}
  click(e){if(!this.image)return;const r=this.canvas.getBoundingClientRect(),x=(e.clientX-r.left)*this.canvas.width/r.width,y=(e.clientY-r.top)*this.canvas.height/r.height;let best=null,bd=Infinity;for(const[k,p]of Object.entries(this.points)){const d=Math.hypot(p.x-x,p.y-y);if(d<bd){best=k;bd=d}}if(best&&bd<Math.max(this.canvas.width,this.canvas.height)*.035){this.selected=best;this.points[best]={x,y}}else{const next=this.order.find(k=>!this.points[k]);if(next){this.selected=next;this.points[next]={x,y}}}this.draw();this.onchange?.()}
  undo(){const last=[...this.order].reverse().find(k=>this.points[k]);if(last)delete this.points[last];this.selected=null;this.draw();this.onchange?.()}
  clear(){this.points={};this.selected=null;this.draw();this.onchange?.()}
  complete(){return this.order.every(k=>this.points[k])}
  nextLabel(){return this.order.find(k=>!this.points[k])||'COMPLETE'}
  draw(){const c=this.ctx;c.clearRect(0,0,this.canvas.width,this.canvas.height);if(!this.image)return;c.drawImage(this.image,0,0);c.lineWidth=Math.max(3,this.canvas.width*.006);c.strokeStyle='#00e5ff';c.fillStyle='#ffea00';c.lineCap='round';for(const[a,b]of this.edges){if(this.points[a]&&this.points[b]){c.beginPath();c.moveTo(this.points[a].x,this.points[a].y);c.lineTo(this.points[b].x,this.points[b].y);c.stroke()}}const rr=Math.max(6,this.canvas.width*.012);for(const[k,p]of Object.entries(this.points)){c.beginPath();c.arc(p.x,p.y,rr,0,Math.PI*2);c.fill();c.strokeStyle='#111';c.lineWidth=Math.max(2,this.canvas.width*.003);c.stroke();c.fillStyle='#fff';c.font=`${Math.max(12,this.canvas.width*.018)}px sans-serif`;c.fillText(k,p.x+rr+3,p.y-rr-2);c.fillStyle='#ffea00';c.strokeStyle='#00e5ff';c.lineWidth=Math.max(3,this.canvas.width*.006)}}
  exportPng(){return this.canvas.toDataURL('image/png')}
  normalized(){const w=this.canvas.width,h=this.canvas.height,o={};for(const[k,p]of Object.entries(this.points))o[k]={x:+(p.x/w).toFixed(5),y:+(p.y/h).toFixed(5)};return o}
}
